# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PcuBNZVwmoWvrTllIsjpTzi21PDYZREz
"""

!pip install openai
!pip install apify-client
!pip install langchain_openai
!pip install Document
!pip install langchain
!pip install langchain_community
!pip install pyng
!pip install streamlit
!pip install pyngrok

import json

# Commented out IPython magic to ensure Python compatibility.
# 
# %%writefile app.py
# import streamlit as st
# import requests
# import os
# from bs4 import BeautifulSoup
# import openai
# from openai import OpenAI
# from langchain.docstore.document import Document
# from langchain.indexes import VectorstoreIndexCreator
# from langchain_community.utilities import ApifyWrapper
# from langchain.embeddings import OpenAIEmbeddings
# from langchain_openai import OpenAI
# import json
# 
# 
# os.environ["APIFY_API_TOKEN"] = ""
# 
# os.environ["OPENAI_API_KEY"] = ""
# 
# apify = ApifyWrapper()
# 
# run_input = {
#         "startUrls": [{ "url": "https://connect.illinoisstate.edu/apply/" }],
#         "startUrls2": [{ "url": "https://illinoisstate.edu/apply/preparation/" }],
#         "startUrls3": [{ "url": "https://connect.illinoisstate.edu/apply/" }],
#         "startUrls4": [{ "url": "https://illinoisstate.edu/apply/graduate/" }],
#         "startUrls5": [{ "url": "https://illinoisstate.edu/admissions/graduate/requirements/" }],
#         "startUrls6": [{ "url": "https://illinoisstate.edu/academics/computer-science-masters/" }],
#         "startUrls7": [{ "url": "https://illinoisstate.edu/admissions/transfer/" }],
#         "startUrls8": [{ "url": "https://housing.illinoisstate.edu/locations/" }],
#         "startUrls9": [{ "url": "https://financialaid.illinoisstate.edu/paying/https://financialaid.illinoisstate.edu/paying/" }],
#         "startUrls10": [{ "url": "https://studentaccounts.illinoisstate.edu/billing/" }],
#         "startUrls11": [{ "url": "https://studentaccounts.illinoisstate.edu/billing/due-dates/" }],
#         "startUrls12": [{ "url": "https://studentaccounts.illinoisstate.edu/billing/undergraduate-tuition/#Tuition-Rates1"}],
#         "startUrls13": [{ "url": "https://studentaccounts.illinoisstate.edu/billing-made-easy/new-student/"}],
#         "startUrls14": [{ "url": "https://studentaccounts.illinoisstate.edu/billing-made-easy/how-to/erefunds/"}],
#         "startUrls15": [{ "url": "https://illinoisstate.edu/admissions/scholarships/transfer/"}],
#         "startUrls16": [{ "url": "https://financialaid.illinoisstate.edu/scholarships/"}],
#         "startUrls17": [{ "url": "https://illinoisstate.edu/admissions/transfer/on-the-spot/"}],
#         "startUrls18": [{ "url": "https://illinoisstate.edu/academics/pre-professional/"}],
#         "startUrls19": [{ "url": "https://illinoisstate.edu/apply/international/"}],
#         "startUrls20": [{ "url": "https://illinoisstate.edu/admissions/contact/"}],
#         "startUrls21": [{ "url": "https://illinoisstate.edu/admissions/contact/staff/"}],
#         "startUrls22": [{ "url": "https://illinoisstate.edu/apply/preparation/#freshman"}],
#         "startUrls23": [{ "url": "https://illinoisstate.edu/admissions/freshman-requirements/#statement"}],
#         "startUrls24": [{ "url": "https://illinoisstate.edu/admissions/international/requirements/"}],
#         "startUrls25": [{ "url": "https://connect.illinoisstate.edu/portal/summer"}]
# 
# 
# 
# 
# }
# 
# loader = apify.call_actor(
#     actor_id="apify/website-content-crawler",
#     run_input=run_input,
#     dataset_mapping_function=lambda item: Document(
#         page_content=item["text"] or "", metadata={"source": item["url"]}
#     ),
# )
# 
# 
# 
# index = VectorstoreIndexCreator(embedding=OpenAIEmbeddings()).from_loaders([loader])
# 
# def main():
#   st.title("Admissions Assistant")
#   user_input = st.text_input("Welcome to Illinois State University Admissions chatbot assistant! As me a question:")
#   if st.button("Submit"):
#       response = index.query_with_sources(user_input, llm=OpenAI())
#       #ans = json.loads(response)
#       st.write("Certenly! here is how:", response)
# 
# if __name__ == "__main__":
#       main()
#

!streamlit run app.py&>/dev/null&

!pgrep streamlit

!ngrok authtoken [authtoken]

# Run ngrok to expose Streamlit app
from pyngrok import ngrok
# Start ngrok tunnel

public_url = ngrok.connect(addr='8501')
print("Streamlit app can be accessed at:", public_url)

!find . -name \*.pyc -delete

!update-alternatives --install /usr/bin/python2 python2.4.2 /usr/bin/python2.4.2